#!/usr/bin/env bash
#
# USAGE:
#
# In `private-ngraph-cpp/build`, run:
# `./third-party/argon_transformer/src/ext_nnp_transformer/test/run_selected_unit_test.sh`
#

# Environment setup
set -u

# The directory of this script
declare THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Hard coded to 5 dirs upwards, currently we're in
# `private-ngraph-cpp/build/third-party/argon_transformer/src/ext_nnp_transformer/test/run_selected_unit_test.sh`
BUILD_DIR=${THIS_SCRIPT_DIR}/../../../../..
UNIT_TEST_EXEC="${BUILD_DIR}/test/unit-test"

# Concatenate array as a str
function get_gtest_filter_str {
    # Prefix
    echo -n ""
    # Body
    local d=":";
    echo -n "$1";
    shift;
    printf "%s" "${@/#/$d}";
    # Postfix
    echo -n ""
}

declare -a enabled_tests=(
    "NNP_TESTER.aliased_output"
    "NNP_TESTER.parameter_as_output"
    "NNP_TESTER.ab"
    "NNP_TESTER.abc"
    "NNP_TESTER.abc_int64"
    "NNP_TESTER.multiple_result"
    "NNP_TESTER.max_trivial"
    "NNP_TESTER.max_trivial_5d"
    "NNP_TESTER.max_to_scalar"
    "NNP_TESTER.max_matrix_columns"
    "NNP_TESTER.max_matrix_rows"
    "NNP_TESTER.max_3d_to_matrix_most_sig"
    "NNP_TESTER.max_3d_to_matrix_least_sig"
    "NNP_TESTER.max_3d_to_vector"
    "NNP_TESTER.max_3d_to_scalar"
    "NNP_TESTER.min_trivial"
    "NNP_TESTER.min_trivial_5d"
    "NNP_TESTER.min_to_scalar"
    "NNP_TESTER.min_matrix_columns"
    "NNP_TESTER.min_matrix_rows"
    "NNP_TESTER.min_3d_to_matrix_most_sig"
    "NNP_TESTER.min_3d_to_matrix_least_sig"
    "NNP_TESTER.min_3d_to_vector"
    "NNP_TESTER.min_3d_to_scalar"
    # "NNP_TESTER.abs"
    # "NNP_TESTER.ceiling"
    "NNP_TESTER.concat_matrix_colwise"
    "NNP_TESTER.concat_matrix_rowwise"
    "NNP_TESTER.concat_matrix_int64"
    "NNP_TESTER.concat_vector"
    "NNP_TESTER.concat_5d"
    "NNP_TESTER.divide"
    # "NNP_TESTER.divide_by_zero_float32"
    # "NNP_TESTER.divide_by_zero_int32"
    "NNP_TESTER.equal"
    # "NNP_TESTER.floor"
    # "NNP_TESTER.dot_0_0"
    # "NNP_TESTER.dot_matrix_2x0_0x2"
    # "NNP_TESTER.dot_matrix_0x2_2x0"
    # "NNP_TESTER.dot_matrix_3x2_2x0"
    # "NNP_TESTER.dot_scalar_0x2"
    "NNP_TESTER.dot1d"
    "NNP_TESTER.dot2d"
    "NNP_TESTER.dot3d_3d"
    "NNP_TESTER.dot3d_2d"
    "NNP_TESTER.dot_scalar_tensor_arg0"
    "NNP_TESTER.dot_scalar_tensor_arg1"
    "NNP_TESTER.dot_scalar_scalar"
    "NNP_TESTER.dot_matrix_vector"
    "NNP_TESTER.dot_matrix_vector_int64"
    "NNP_TESTER.greater"
    "NNP_TESTER.greatereq"
    "NNP_TESTER.less"
    "NNP_TESTER.lesseq"
    "NNP_TESTER.lesseq_bool"
    # "NNP_TESTER.log"
    "NNP_TESTER.maximum"
    "NNP_TESTER.minimum"
    # "NNP_TESTER.negative"
    "NNP_TESTER.notequal"
    "NNP_TESTER.select"
    "NNP_TESTER.subtract"
    "NNP_TESTER.tensor_constant"
    "NNP_TESTER.tensor_constant_with_op"
    "NNP_TESTER.constant_broadcast"
    # "NNP_TESTER.function_call"
    "NNP_TESTER.broadcast_scalar_vector"
    "NNP_TESTER.broadcast_scalar_matrix"
    "NNP_TESTER.broadcast_scalar_tensor"
    "NNP_TESTER.broadcast_trivial"
    "NNP_TESTER.broadcast_vector_colwise"
    "NNP_TESTER.broadcast_vector_rowwise"
    "NNP_TESTER.broadcast_vector_rowwise_64"
    "NNP_TESTER.broadcast_matrix_0"
    "NNP_TESTER.broadcast_matrix_1"
    "NNP_TESTER.broadcast_matrix_2"
    "NNP_TESTER.convert_int32_float32"
    "NNP_TESTER.convert_int32_bool"
    "NNP_TESTER.convert_float32_bool"
    # "NNP_TESTER.reduce_trivial"
    # "NNP_TESTER.reduce_to_scalar"
    # "NNP_TESTER.reduce_matrix_columns"
    # "NNP_TESTER.reduce_matrix_rows"
    # "NNP_TESTER.reduce_matrix_rows_zero"
    # "NNP_TESTER.reduce_matrix_cols_zero"
    # "NNP_TESTER.reduce_vector_zero"
    # "NNP_TESTER.reduce_matrix_to_scalar_zero_by_zero"
    # "NNP_TESTER.reduce_3d_to_vector"
    "NNP_TESTER.relu_2Dfprop"
    "NNP_TESTER.relu_4Dfprop"
    "NNP_TESTER.fuse_max_with_constant_zero_input_as_relu"
    #"NNP_TESTER.relu_2Dbackprop"
    #"NNP_TESTER.relu_4Dbackprop"
    #"NNP_TESTER.backwards_relu"
    "NNP_TESTER.reshape_t2v_012"
    "NNP_TESTER.reshape_t2s_012"
    "NNP_TESTER.reshape_t2s_120"
    "NNP_TESTER.reshape_s2t"
    "NNP_TESTER.reshape_v2m_col"
    "NNP_TESTER.reshape_v2m_row"
    "NNP_TESTER.reshape_v2t_middle"
    "NNP_TESTER.reshape_m2m_same"
    "NNP_TESTER.reshape_m2m_transpose"
    "NNP_TESTER.reshape_m2m_dim_change_transpose"
    "NNP_TESTER.reshape_6d"
    # "NNP_TESTER.sin"
    # "NNP_TESTER.cos"
    # "NNP_TESTER.tan"
    # "NNP_TESTER.asin"
    # "NNP_TESTER.acos"
    # "NNP_TESTER.atan"
    # "NNP_TESTER.sinh"
    # "NNP_TESTER.cosh"
    # "NNP_TESTER.tanh"
    # "NNP_TESTER.exp"
    "NNP_TESTER.slice_scalar"
    "NNP_TESTER.slice_matrix"
    "NNP_TESTER.slice_vector"
    # "NNP_TESTER.slice_matrix_strided"
    "NNP_TESTER.slice_3d"
    # "NNP_TESTER.slice_3d_strided"
    # "NNP_TESTER.slice_3d_strided_different_strides"
    # "NNP_TESTER.scalar_constant_float32"
    "NNP_TESTER.scalar_constant_int64"
    # "NNP_TESTER.tensor_constant_float32"
    "NNP_TESTER.tensor_constant_int64"
    "NNP_TESTER.sum_trivial"
    "NNP_TESTER.sum_trivial_5d"
    "NNP_TESTER.sum_to_scalar"
    "NNP_TESTER.sum_matrix_columns"
    "NNP_TESTER.sum_matrix_rows"
    # "NNP_TESTER.sum_matrix_rows_zero"
    # "NNP_TESTER.sum_matrix_cols_zero"
    # "NNP_TESTER.sum_vector_zero"
    # "NNP_TESTER.sum_matrix_to_scalar_zero_by_zero"
    "NNP_TESTER.sum_3d_to_matrix_most_sig"
    "NNP_TESTER.sum_3d_to_matrix_least_sig"
    "NNP_TESTER.sum_3d_to_vector"
    "NNP_TESTER.sum_3d_to_scalar"
    # "NNP_TESTER.sum_3d_eliminate_zero_dim"
    # "NNP_TESTER.sum_to_scalar_stable"
    # "NNP_TESTER.sum_3d_to_vector_stable"
    # "NNP_TESTER.sign"
    # "NNP_TESTER.power"
    "NNP_TESTER.constant_equality_bool"
    # "NNP_TESTER.sqrt"
    # "NNP_TESTER.replace_slice_scalar"
    # "NNP_TESTER.replace_slice_matrix"
    # "NNP_TESTER.replace_slice_vector"
    # "NNP_TESTER.one_hot_scalar_2_in_3"
    # "NNP_TESTER.one_hot_scalar_1_in_3"
    # "NNP_TESTER.one_hot_scalar_0_in_3"
    # "NNP_TESTER.one_hot_scalar_fp_nonint_in_3"
    # "NNP_TESTER.one_hot_scalar_oob_in_3"
    # "NNP_TESTER.one_hot_vector_0"
    # "NNP_TESTER.one_hot_vector_1"
    # "NNP_TESTER.one_hot_vector_1_barely_oob"
    # "NNP_TESTER.one_hot_vector_1_far_oob"
    # "NNP_TESTER.one_hot_matrix_0"
    # "NNP_TESTER.one_hot_vector_1_fp"
    # "NNP_TESTER.one_hot_vector_1_fp_nonint"
    # "NNP_TESTER.replace_slice_3d"
    # "NNP_TESTER.replace_slice_3d_strided"
    # "NNP_TESTER.replace_slice_3d_strided_different_strides"
    # "NNP_TESTER.max_pool_1d_1channel_1image"
    # "NNP_TESTER.max_pool_1d_1channel_2image"
    # "NNP_TESTER.max_pool_1d_2channel_2image"
    # "NNP_TESTER.max_pool_2d_2channel_2image"
    # "NNP_TESTER.max_pool_2d_1channel_1image_overpadded"
    # "NNP_TESTER.max_pool_2d_1channel_1image_strided"
    "NNP_TESTER.not"
    # "NNP_TESTER.reverse_0d"
    # "NNP_TESTER.reverse_1d_nochange"
    # "NNP_TESTER.reverse_1d_0"
    # "NNP_TESTER.reverse_2d_nochange"
    # "NNP_TESTER.reverse_2d_0"
    # "NNP_TESTER.reverse_2d_1"
    # "NNP_TESTER.reverse_2d_01"
    # "NNP_TESTER.reverse_3d_nochange"
    # "NNP_TESTER.reverse_3d_0"
    # "NNP_TESTER.reverse_3d_1"
    # "NNP_TESTER.reverse_3d_2"
    # "NNP_TESTER.reverse_3d_01"
    # "NNP_TESTER.reverse_3d_02"
    # "NNP_TESTER.reverse_3d_12"
    # "NNP_TESTER.reverse_3d_012"
    # "NNP_TESTER.numeric_float_nan"
    # "NNP_TESTER.numeric_double_nan"
    # "NNP_TESTER.numeric_float_inf"
    # "NNP_TESTER.numeric_double_inf"
    "NNP_TESTER.abc_tbb"
    # "NNP_TESTER.reduce_window_emulating_max_pool_1d_1channel_1image"
    # "NNP_TESTER.reduce_window_emulating_max_pool_1d_1channel_2image"
    # "NNP_TESTER.reduce_window_emulating_max_pool_1d_2channel_2image"
    # "NNP_TESTER.reduce_window_emulating_max_pool_2d_2channel_2image"
    # "NNP_TESTER.reduce_window_emulating_max_pool_2d_1channel_1image_strided"
    # "NNP_TESTER.select_and_scatter_with_overlap"
    # "NNP_TESTER.select_and_scatter_without_overlap"
    # "NNP_TESTER.select_and_scatter_3d_without_overlap"
    # "NNP_TESTER.zero_sized_abs"
    # "NNP_TESTER.zero_sized_ceiling"
    # "NNP_TESTER.zero_sized_exp"
    # "NNP_TESTER.zero_sized_floor"
    # "NNP_TESTER.zero_sized_log"
    # "NNP_TESTER.zero_sized_negative"
    # "NNP_TESTER.zero_sized_not"
    # "NNP_TESTER.zero_sized_sign"
    # "NNP_TESTER.zero_sized_sqrt"
    # "NNP_TESTER.zero_sized_sin"
    # "NNP_TESTER.zero_sized_sinh"
    # "NNP_TESTER.zero_sized_cos"
    # "NNP_TESTER.zero_sized_cosh"
    # "NNP_TESTER.zero_sized_tan"
    # "NNP_TESTER.zero_sized_tanh"
    # "NNP_TESTER.zero_sized_asin"
    # "NNP_TESTER.zero_sized_acos"
    # "NNP_TESTER.zero_sized_atan"
    # "NNP_TESTER.zero_sized_add"
    # "NNP_TESTER.zero_sized_divide"
    # "NNP_TESTER.zero_sized_eq"
    # "NNP_TESTER.zero_sized_greater"
    # "NNP_TESTER.zero_sized_greatereq"
    # "NNP_TESTER.zero_sized_less"
    # "NNP_TESTER.zero_sized_lesseq"
    # "NNP_TESTER.zero_sized_maximum"
    # "NNP_TESTER.zero_sized_minimum"
    # "NNP_TESTER.zero_sized_multiply"
    # "NNP_TESTER.zero_sized_not_equal"
    # "NNP_TESTER.zero_sized_power"
    # "NNP_TESTER.zero_sized_subtract"
    # "NNP_TESTER.avg_pool_1d_1channel_1image"
    # "NNP_TESTER.avg_pool_1d_1channel_2image"
    # "NNP_TESTER.avg_pool_1d_2channel_2image"
    # "NNP_TESTER.avg_pool_2d_2channel_2image"
    # "NNP_TESTER.avg_pool_2d_1channel_1image_strided"
    # "NNP_TESTER.avg_pool_2d_1channel_1image_padded"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded_only_below"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded_only_above"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded_3x3"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded_3x3_strided"
    # "NNP_TESTER.avg_pool_2d_2channel_2image_padded_3x3_strided_uneven"
    # "NNP_TESTER.pad_interior_1d"
    # "NNP_TESTER.pad_exterior_1d"
    # "NNP_TESTER.pad_interior_exterior_1d"
    # "NNP_TESTER.pad_interior_exterior_2d"
    # "NNP_TESTER.pad_exterior_2d_0x0"
    # "NNP_TESTER.pad_exterior_2d_0x3"
    # "NNP_TESTER.pad_exterior_2d_3x0"
    # "NNP_TESTER.pad_interior_exterior_4d_2x0x3x2"
    # "NNP_TESTER.convolution_2d_1item"
    # "NNP_TESTER.convolution_2d_1item_padded_1_1x1_1"
    # "NNP_TESTER.convolution_2d_1item_padded_2_3x4_5"
    # "NNP_TESTER.convolution_2d_2items"
    # "NNP_TESTER.convolution_2d_2items_strided"
    # "NNP_TESTER.convolution_2d_2items_strided_padded"
    # "NNP_TESTER.convolution_2d_2items_strided_padded_same"
    # "NNP_TESTER.convolution_2d_2items_dilated"
    # "NNP_TESTER.convolution_2d_2items_dilated_padded"
    # "NNP_TESTER.convolution_3d_2items"
    # "NNP_TESTER.convolution_4d_2items"
    # "NNP_TESTER.convolution_4d_4items"
    # "NNP_TESTER.convolution_4d_4items_padded_neg"
    # "NNP_TESTER.convolution_4d_4items_strided"
    # "NNP_TESTER.convolution_4d_4items_dilated"
    # "NNP_TESTER.convolution_4d_4items_strided_dilated"
    # "NNP_TESTER.convolution_4d_4items_strided_dilated_padded"
    # "NNP_TESTER.convolution_4d_4items_strided_dilated_padded_neg"
    # "NNP_TESTER.convolution_4d_4items_strided_dilated_padded_same"
    # "NNP_TESTER.convolution_2d_1item_1o1i_data_dilated"
    # "NNP_TESTER.convolution_2d_1item_2o1i_data_dilated"
    # "NNP_TESTER.convolution_2d_1item_2o2i_data_dilated"
    # "NNP_TESTER.convolution_2d_1item_5o3i_data_dilated"
    # "NNP_TESTER.convolution_2d_2item_5o3i_data_dilated"
    # "NNP_TESTER.convolution_2d_8item_large_5o3i_data_dilated"
    # "NNP_TESTER.convolution_2d_8item_large_5o3i_uneven_filter_data_dilated"
    # "NNP_TESTER.convolution_2d_8item_large_5o3i_uneven_filter_uneven_data_dilation_data_dilated"
    # "NNP_TESTER.convolution_3d_2item_large_5o3i_uneven_filter_uneven_data_dilation_data_dilated"
    # "NNP_TESTER.convolution_3d_1item_large_5o3i_padded_uneven_filter_uneven_data_dilation_data_dilated"
    # "NNP_TESTER.convolution_3d_2item_large_5o3i_padded_strided_uneven_filter_uneven_data_dilation_data_dilated"
    # "NNP_TESTER.convolution_3d_2item_large_5o3i_padded_strided_uneven_filter_uneven_data_dilation_filter_dilated_data_dilated"
)
"${UNIT_TEST_EXEC}" --gtest_filter=$(get_gtest_filter_str ${enabled_tests[@]})
